# Generated by Django 4.0.6 on 2022-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SF', 'Sci-fi'), ('DR', 'Drama'), ('HO', 'Horror'), ('UN', 'Unknown')], default='UN', max_length=55),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
